// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbqueries

import (
	"time"
)

type Author struct {
	ID   int64
	Name string
}

type Quote struct {
	ID        int64
	Content   string
	AuthorID  int64
	DateAdded time.Time
}

type QuoteTag struct {
	QuoteID int64
	TagID   int64
}

type Tag struct {
	ID   int64
	Name string
}
